#!/bin/bash

test -f /sbin/openrc-init && {
  sed -i \
    -e 's+#deb http://pkgmaster.devuan.org/devuan ceres main+deb http://pkgmaster.devuan.org/devuan ceres main+g' \
    -e 's+#deb http://pkgmaster.devuan.org/merged ceres main+deb http://pkgmaster.devuan.org/merged ceres main+g' \
    -e 's+#deb http://pkgmaster.devuan.org/devuan beowulf main+deb http://pkgmaster.devuan.org/devuan beowulf main+g' \
    -e 's+#deb http://pkgmaster.devuan.org/merged beowulf main+deb http://pkgmaster.devuan.org/merged beowulf main+g' \
    /etc/apt/sources.list.d/devuan-repo.list

  sed -i \
    -e 's+#deb http://archive.ubuntu.com/ubuntu focal main restricted universe multiverse+deb http://archive.ubuntu.com/ubuntu focal main restricted universe multiverse+g' \
    -e 's+#deb http://archive.ubuntu.com/ubuntu focal-security main restricted universe multiverse+deb http://archive.ubuntu.com/ubuntu focal-security main restricted universe multiverse+g' \
    -e 's+#deb http://archive.ubuntu.com/ubuntu focal-updates main restricted universe multiverse+deb http://archive.ubuntu.com/ubuntu focal-updates main restricted universe multiverse+g' \
    /etc/apt/sources.list.d/ubuntu-focal-repo.list

  sed -i \
    -e 's+deb http://archive.ubuntu.com/ubuntu bionic main restricted universe multiverse+#deb http://archive.ubuntu.com/ubuntu bionic main restricted universe multiverse+g' \
    -e 's+deb http://archive.ubuntu.com/ubuntu bionic-security main restricted universe multiverse+#deb http://archive.ubuntu.com/ubuntu bionic-security main restricted universe multiverse+g' \
    -e's+deb http://archive.ubuntu.com/ubuntu bionic-updates main restricted universe multiverse+#deb http://archive.ubuntu.com/ubuntu bionic-updates main restricted universe multiverse+g' \
    /etc/apt/sources.list.d/ubuntu-bionic-repo.list

  apt -qq update
	} || {
  sed -i \
    -e 's+deb http://archive.ubuntu.com/ubuntu bionic main restricted universe multiverse+#deb http://archive.ubuntu.com/ubuntu bionic main restricted universe multiverse+g' \
    -e 's+deb http://archive.ubuntu.com/ubuntu bionic-security main restricted universe multiverse+#deb http://archive.ubuntu.com/ubuntu bionic-security main restricted universe multiverse+g' \
    -e's+deb http://archive.ubuntu.com/ubuntu bionic-updates main restricted universe multiverse+#deb http://archive.ubuntu.com/ubuntu bionic-updates main restricted universe multiverse+g' \
    /etc/apt/sources.list.d/ubuntu-bionic-repo.list

  apt -qq update
	}

exit
