#!/bin/bash

test -f /sbin/openrc-init && {
	sed -i \
		-e 's+#deb http://archive.ubuntu.com/ubuntu focal main restricted universe multiverse+deb http://archive.ubuntu.com/ubuntu focal main restricted universe multiverse+g' \
		-e 's+#deb http://archive.ubuntu.com/ubuntu focal-security main restricted universe multiverse+deb http://archive.ubuntu.com/ubuntu focal-security main restricted universe multiverse+g' \
		-e 's+#deb http://archive.ubuntu.com/ubuntu focal-updates main restricted universe multiverse+deb http://archive.ubuntu.com/ubuntu focal-updates main restricted universe multiverse+g' \
		/etc/apt/sources.list.d/ubuntu-focal-repo.list

	sed -i \
		-e 's+deb http://archive.ubuntu.com/ubuntu bionic main restricted universe multiverse+#deb http://archive.ubuntu.com/ubuntu bionic main restricted universe multiverse+g' \
		-e 's+deb http://archive.ubuntu.com/ubuntu bionic-security main restricted universe multiverse+#deb http://archive.ubuntu.com/ubuntu bionic-security main restricted universe multiverse+g' \
		-e's+deb http://archive.ubuntu.com/ubuntu bionic-updates main restricted universe multiverse+#deb http://archive.ubuntu.com/ubuntu bionic-updates main restricted universe multiverse+g' \
		/etc/apt/sources.list.d/ubuntu-bionic-repo.list

	>> /etc/apt/preferences printf "%s\n" \
		'Package: base-files' \
		'Pin: release *' \
		'Pin-Priority: -1' \
		'' \
		'Package: bluez' \
		'Pin: release *' \
		'Pin-Priority: -1' \
		'' \
		'Package: cgroupfs-mount' \
		'Pin: release *' \
		'Pin-Priority: -1' \
		'' \
		'Package: dash' \
		'Pin: release *' \
		'Pin-Priority: -1' \
		'' \
		'Package: dictionaries-common' \
		'Pin: release *' \
		'Pin-Priority: -1' \
		'' \
		'Package: initramfs-tools' \
		'Pin: release *' \
		'Pin-Priority: -1' \
		'' \
		'Package: initramfs-tools-bin' \
		'Pin: release *' \
		'Pin-Priority: -1' \
		'' \
		'Package: initramfs-tools-core' \
		'Pin: release *' \
		'Pin-Priority: -1' \
		'' \
		'Package: libpulse-mainloop-glib0' \
		'Pin: release *' \
		'Pin-Priority: -1' \
		'' \
		'Package: libpulse0' \
		'Pin: release *' \
		'Pin-Priority: -1' \
		'' \
		'Package: libpulsedsp' \
		'Pin: release *' \
		'Pin-Priority: -1' \
		'' \
		'Package: libplymouth5' \
		'Pin: release *' \
		'Pin-Priority: -1'
		'' \
		'Package: plasma-discover' \
		'Pin: release *' \
		'Pin-Priority: -1' \
		'' \
		'Package: plasma-discover-common' \
		'Pin: release *' \
		'Pin-Priority: -1' \
		'' \
		'Package: plasma-discover-backend-flatpak' \
		'Pin: release *' \
		'Pin-Priority: -1' \
		'' \
		'Package: plasma-pa' \
		'Pin: release *' \
		'Pin-Priority: -1' \
		'' \
		'Package: pulseaudio' \
		'Pin: release *' \
		'Pin-Priority: -1' \
		'' \
		'Package: pulseaudio-module-bluetooth' \
		'Pin: release *' \
		'Pin-Priority: -1' \
		'' \
		'Package: plymouth' \
		'Pin: release *' \
		'Pin-Priority: -1' \
		'' \
		'Package: plymouth-theme-spinner' \
		'Pin: release *' \
		'Pin-Priority: -1' \
		'Package: plymouth-label' \
		'Pin: release *' \
		'Pin-Priority: -1' \
		'' \
		'Package: plymouth-themes' \
		'Pin: release *' \
		'Pin-Priority: -1' \
		'' \
		'Package: pulseaudio-utils' \
		'Pin: release *' \
		'Pin-Priority: -1' \
		'' \
		'Package: samba-common' \
		'Pin: release *' \
		'Pin-Priority: -1' \
		'' \
		'Package: snapd' \
		'Pin: release *' \
		'Pin-Priority: -1' \
		'' \
		'Package: sudo' \
		'Pin: version 1.9.1-2' \
		'Pin-Priority: -1' \
		'' \
		'Package: systemd' \
		'Pin: release *' \
		'Pin-Priority: -1' \
		'' \
		'Package: ssl-cert' \
		'Pin: release *' \
		'Pin-Priority: -1' \
		'' \
		'Package: ufw' \
		'Pin: release *' \
		'Pin-Priority: -1' \
		'' \
		'Package: xterm' \
		'Pin: release *' \
		'Pin-Priority: -1' \
		'' \
		'########################' \
		'#  Repository Priority #' \
		'########################' \
		'' \
		'Package: *' \
		'Pin: release o=user' \
		'Pin-Priority: 700' \
		'' \
		'Package: *' \
		'Pin: origin archive.neon.kde.org' \
		'Pin-Priority: 700' \
		'' \
		'Package: *' \
		'Pin: release o=focal' \
		'Pin-Priority: 600' \
		'' \
		'Package: *' \
		'Pin: origin archive.ubuntu.com' \
		'Pin-Priority: 600' \
		'' 
} || {
	sed -i \
		-e 's+deb http://archive.ubuntu.com/ubuntu bionic main restricted universe multiverse+#deb http://archive.ubuntu.com/ubuntu bionic main restricted universe multiverse+g' \
		-e 's+deb http://archive.ubuntu.com/ubuntu bionic-security main restricted universe multiverse+#deb http://archive.ubuntu.com/ubuntu bionic-security main restricted universe multiverse+g' \
		-e's+deb http://archive.ubuntu.com/ubuntu bionic-updates main restricted universe multiverse+#deb http://archive.ubuntu.com/ubuntu bionic-updates main restricted universe multiverse+g' \
		/etc/apt/sources.list.d/ubuntu-bionic-repo.list

	>> /etc/apt/preferences printf "%s\n" \
		'Package: base-files' \
		'Pin: release *' \
		'Pin-Priority: -1' \
		'' \
		'Package: dash' \
		'Pin: release *' \
		'Pin-Priority: -1' \
		'' \
		'Package: initramfs-tools' \
		'Pin: release *' \
		'Pin-Priority: -1' \
		'' \
		'Package: initramfs-tools-bin' \
		'Pin: release *' \
		'Pin-Priority: -1' \
		'' \
		'Package: initramfs-tools-core' \
		'Pin: release *' \
		'Pin-Priority: -1' \
		'' \
		'Package: plasma-pa' \
		'Pin: release *' \
		'Pin-Priority: -1' \
		'' \
		'Package: plymouth' \
		'Pin: release *' \
		'Pin-Priority: -1' \
		'' \
		'Package: plymouth-theme-spinner' \
		'Pin: release *' \
		'Pin-Priority: -1' \
		'' \
		'Package: sudo' \
		'Pin: version 1.9.1-2' \
		'Pin-Priority: -1' \
		'' \
		'Package: ufw' \
		'Pin: release *' \
		'Pin-Priority: -1' \
		'' \
		'Package: xterm' \
		'Pin: release *' \
		'Pin-Priority: -1' \
		'' 
}

apt -qq update
