#!/bin/bash

OLD_FILES='
    /etc/apt/preferences
    /etc/apt/sources.list.d/devuan-beowulf-repo.list
    /etc/apt/sources.list.d/devuan-ceres-repo.list
    /etc/apt/sources.list.d/neon-repos.list
    /etc/apt/sources.list.d/ubuntu-bionic-repo.list
    /etc/apt/sources.list.d/ubuntu-focal-repo.list
    /etc/apt/sources.list.d/ubuntu-repos.list
'
rm -r $OLD_FILES || true

apt-key del \
    55751E5D \
    1B69B2DA \
    541922FB \
	BB23C00C61FC752C \
	3B4FE6ACC0B21F32 \
	871920D1991BC93C \
    1118213C > /dev/null

